name: html2md
description: Convert html to markdown. A simplify version of node's `turndown`.
version: 0.0.1
homepage: https://github.com/jarontai/html2md
author: jarontai <jaroncn@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  path: ^1.4.1
  html: any

dev_dependencies:
  test: ^0.12.0
